### ISSUE TITLE
Card Wrapper Became Untidy Because Profile Picture :)

### ISSUE THREAD

**Issue by andrianwinata** [rickt25/holosimp#4]

**Comment by rickt25** [comment]
Please provide more information

**Comment by andrianwinata** [comment]
Thanks for your attention

**Comment by rickt25** [comment]
The issue has been fixed by mr. @andrianwinata on commit [Fix Thumbnails](https://github.com/rickt25/holosimp/commit/df6b2811767d61883fecde791d1a4bde7f77f1ed)
